spring:
  datasource:
    username: bolitao
    password: bolitao
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.79.129:3306/boliblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #    url: jdbc:p6spy:mysql://127.0.0.1:3306/boliblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  devtools:
    restart:
      poll-interval: 2500ms
      quiet-period: 2200ms
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
bolitao:
  conf:
    secret: thisisatestjwtsecreteyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQthisisatestjwtsecret!
    expire: 604800
    header: Authorization
server:
  port: 8899
shiro-redis:
  enabled: true
  redis-manager:
    password: bolitao
    host: 192.168.79.129:6379
