spring:
  datasource:
    username: bolitao
    password: bolitao
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boliblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  devtools:
    restart:
      poll-interval: 2500ms
      quiet-period: 2200ms
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
